spring.application.name=voyage
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/voyagebd
spring.datasource.username=postgres
spring.datasource.password=P@sser123
spring.datasource.schema=classpath:/schema.sql
# spring.thymeleaf
# server.error.whitelabel.enabled=false
spring.security.user.name=user
spring.security.user.password=pass
spring.devtools.restart.enabled=false



server.error.include-message=always
server.error.include-binding-errors=always
spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-http-post-size=20971520
video.upload.path=upload/video/
videos.static-path=C:/video-tierno
spring.data.rest.base-path=/api
